name: Validate

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  validate-hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: plugin
